---
- name: print variables
  debug:
    msg: "local website directory: {{ web_build_path }}"

- name: Setup environment, python and base packages
  import_tasks: base-packages.yml

- name: Configure firewall
  import_tasks: firewall.yml

- name: Configure webapp and related files
  import_tasks: webapp-setup.yml

- name: Configure nginx and related files
  import_tasks: nginx-setup.yml
