---
- name: install nginx
  package:
    name:
      - nginx
    state: latest
  become: yes

- name: Create nginx config
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

