---
- name: print variables
  debug:
    msg: "local website directory: {{ web_build_path }}"

- name: Setup environment, python and base packages
  import_tasks: base-packages.yml

- name: Configure nginx and related files
  import_tasks: nginx-install.yml

