---
- name: install nginx
  package:
    name:
      - nginx
    state: latest
  become: yes

- name: copy website
  synchronize:
    src: "{{ web_build_path }}/"
    dest: /var/www/html/
    checksum: yes
  become: yes
  notify: restart nginx