---

- name: install nginx
  package:
    name:
      - nginx
    state: latest
  become: yes
  notify: restart nginx

    #  - name: copy index.html
    #    copy:
    #      src: index.html
  #      dest: /usr/share/nginx/html/index.html
  #    become: yes